export const studentsData = [
  {
    id: 1,
    name: "Mainak Shyam",
    company: "Aditya Birla Sunlife Mutual Funds",
    designation: "Relationship Manager",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 2,
    name: "Hanish Atiketi",
    company: "Aditya Birla Sunlife Mutual Funds",
    designation: "Relationship Manager",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 3,
    name: "Gampa Abhishek",
    company: "Aditya Birla Sunlife Mutual Funds",
    designation: "Relationship Manager",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 4,
    name: "Aman Kumar Singh",
    company: "Asian Paints",
    designation: "Sales Officer",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 5,
    name: "Kishore Kunchala",
    company: "Asian Paints",
    designation: "Sales Officer",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 6,
    name: "G Rohan",
    company: "Asian Paints",
    designation: "Sales Officer",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 7,
    name: "Subhajeet Pan",
    company: "Asian Paints",
    designation: "Sales Officer",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 8,
    name: "Sunkara Kalyan",
    company: "Asian Paints",
    designation: "Sales Officer",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 9,
    name: "Kandukuri Varun",
    company: "Asian Paints",
    designation: "Sales Officer",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 10,
    name: "Gajja Harshitha",
    company: "Berkadia",
    designation: "Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 11,
    name: "Konanki Priyanka",
    company: "Berkadia",
    designation: "Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 12,
    name: "Manisha Prasad",
    company: "Berkadia",
    designation: "Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 13,
    name: "Parbati Ghosh",
    company: "Berkadia",
    designation: "Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 14,
    name: "Akshay Thakur",
    company: "Berkadia",
    designation: "Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 15,
    name: "Anshu Masih",
    company: "Berkadia",
    designation: "Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 16,
    name: "Busala Usha Sandhya",
    company: "Berkadia",
    designation: "Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 17,
    name: "Chervirala Vedhavathi",
    company: "Berkadia",
    designation: "Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 18,
    name: "M Jyothsna",
    company: "Berkadia",
    designation: "Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 19,
    name: "Vasavi Desu",
    company: "Berkadia",
    designation: "Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 20,
    name: "Dinesh Allam",
    company: "Berkadia",
    designation: "Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 21,
    name: "Ajay Raja Kolati",
    company: "Berkadia",
    designation: "Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 22,
    name: "V Aakanksha Rao",
    company: "Berkadia",
    designation: "Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 23,
    name: "Vemula Akash",
    company: "Big Basket",
    designation: "BDE",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 24,
    name: "Bobbali Sandhya",
    company: "Birla Opus",
    designation: "Sales Trainee",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 25,
    name: "A Akshita",
    company: "Evoke Technologies",
    designation: "Inside Sales Research Associate - Trainee",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 26,
    name: "V V Harshita",
    company: "Codeyoung",
    designation: "RM,BD and International Sales Executive",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 27,
    name: "A V Tejasvin",
    company: "Codeyoung",
    designation: "International Sales Executive",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 28,
    name: "Yash Lunia",
    company: "Daloopa Inc",
    designation: "Operations Analyst / Financial Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 29,
    name: "Nomula Sameeksha",
    company: "Deloitte",
    designation: "Tax Consultant -I",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 30,
    name: "Khoosbu Gosai",
    company: "Deloitte",
    designation: "Tax Consultant -I",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 31,
    name: "Archana Reddy Velemineti",
    company: "Deloitte",
    designation: "Tax Consultant -I",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 32,
    name: "Sirisha Korada",
    company: "Digital Nest",
    designation:
      "Business Development ,Customer Relationship Management,Community management",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 33,
    name: "Khushi Dangre",
    company: "Value Momentum",
    designation: "HRBP - Operations",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 34,
    name: "Manideepthi Manchala",
    company: "Franklin Templeton",
    designation: "Trainee -Operations",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 35,
    name: "Arkatavemula Varalakshmi",
    company: "Godrej Jersey",
    designation: "Field Sales",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 36,
    name: "Dwarampudi Bhuvana Sri Ahalya",
    company: "Godrej Jersey",
    designation: "Field Sales",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 37,
    name: "Hema Latha Reddy Marthala",
    company: "Godrej Jersey",
    designation: "Field Sales",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 38,
    name: "Aditi Sharma",
    company: "HDFC LIFE",
    designation: "Executive Trainee",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 39,
    name: "Ritesh Kumar",
    company: "HDFC LIFE",
    designation: "Executive Trainee",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 40,
    name: "Jetti Abhiram",
    company: "HDFC LIFE",
    designation: "Executive Trainee",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 41,
    name: "Bhavani Siddhu",
    company: "IDFC First Bank",
    designation: "Executive Trainee",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 42,
    name: "Alankar Sinha",
    company: "Homelane",
    designation: "Senior Executive Relationship Management",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 43,
    name: "Varun Reddy Jukanti",
    company: "Homelane",
    designation: "Senior Executive Relationship Management",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 44,
    name: "Rohan Samala Rohan",
    company: "Homelane",
    designation: "Senior Executive Relationship Management",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 45,
    name: "Madhurita Bandapally",
    company: "Homelane",
    designation: "Senior Executive Relationship Management",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 46,
    name: "Naganjini Boppudi",
    company: "Homelane",
    designation: "Senior Executive Relationship Management",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 47,
    name: "Sravya Kanuganti",
    company: "Homelane",
    designation: "Senior Executive Relationship Management",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 48,
    name: "Purma Jyoshna Reddy",
    company: "Quadrant Technologies",
    designation: "Insides Sales",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 49,
    name: "Avala Deepika",
    company: "ICICI Securities",
    designation: "Executive Trainee",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 50,
    name: "Kannappa Reddy Jayalakshmi",
    company: "ICICI Securities",
    designation: "Relationship Manager",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 51,
    name: "Runja N Chaturvedi",
    company: "IDFC First Bank",
    designation: "Collections and Sales role",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 52,
    name: "Macha Sanjay Netha",
    company: "IDFC First Bank",
    designation: "Collections and Sales role",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 53,
    name: "Anil Kumar Yadav",
    company: "IDFC First Bank",
    designation: "Collections and Sales role",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 54,
    name: "Venu Kumar Gunji",
    company: "IIISTUDIO",
    designation: "Business Development",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 55,
    name: "Yadagiri Santhoshini F",
    company: "INK IT Solutions",
    designation: "Management Trainee - Inside sales",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 56,
    name: "Vijaya Lakshmi Katam",
    company: "KPMG",
    designation: "Tax Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 57,
    name: "Shivam Vishwakarma",
    company: "KPMG",
    designation: "Tax Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 58,
    name: "Vishnubhatla Naga Bhargavi",
    company: "KPMG",
    designation: "Tax Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 59,
    name: "Bondili Renuka Bai",
    company: "KPMG",
    designation: "Tax Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 60,
    name: "Donepudi Nikhila",
    company: "KPMG",
    designation: "Tax Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 61,
    name: "Gondimalla Guru Sai",
    company: "KPMG",
    designation: "Tax Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 62,
    name: "Kondipati Govardhan",
    company: "KPMG",
    designation: "Tax Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 63,
    name: "Nilesh Kumar Deheri",
    company: "KPMG",
    designation: "Tax Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 64,
    name: "Chandana Naikal",
    company: "Lloyd Technologies",
    designation: "Management Trainee",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 65,
    name: "N Venkateshwar Reddy",
    company: "Lloyd Technologies",
    designation: "Management Trainee",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 66,
    name: "Thalari Akhila",
    company: "Axis Bank",
    designation: "Virtual Relationship Manager",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 67,
    name: "Vivek Kumar Srivastava",
    company: "Metrics 4 Analytics",
    designation: "Financial Data & Research Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 68,
    name: "Alankar Chakraborty",
    company: "Oxane Partners",
    designation: "Senior Analyst - Portfolio Management Group",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 69,
    name: "Ashita Sharma",
    company: "Oxane Partners",
    designation: "Senior Analyst - Portfolio Management Group",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 70,
    name: "Chikka Manisha",
    company: "Oxane Partners",
    designation: "Senior Analyst - Portfolio Management Group",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 71,
    name: "K V V S R Varun",
    company: "Oxane Partners",
    designation: "Senior Analyst - Portfolio Management Group",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 72,
    name: "Prakhar Singh",
    company: "Oxane Partners",
    designation: "Senior Analyst - Portfolio Management Group",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 73,
    name: "Managalampally Hamsini",
    company: "Praval Infotech",
    designation: "Branch Sales Manager",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 74,
    name: "Ayushi Kumari",
    company: "Praval Infotech",
    designation: "Business Development Executive",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 75,
    name: "Sukhvinder Kour",
    company: "Praval Infotech",
    designation: "Business Development Executive",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 76,
    name: "M.Durga Manish",
    company: "Praval Infotech",
    designation: "Business Development Executive",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 77,
    name: "Karra Rajender Reddy",
    company: "PRM 360",
    designation: "Junior Scrum Master / Project Coordinator",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 78,
    name: "Parul Thawait",
    company: "Prodapt Solutions",
    designation: "Management Trainee -HR",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 79,
    name: "A Sai Akshay Naidu",
    company: "Evoke Technologies",
    designation: "Inside Sales Research Associate - Trainee",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 80,
    name: "Sourabh Kumar",
    company: "Zeneith Forex",
    designation: "Trainee/Executive – Sales",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 81,
    name: "Prashidam Rawani",
    company: "Zeneith Forex",
    designation: "Trainee/Executive – Sales",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 82,
    name: "Sneha Allam",
    company: "Quixy",
    designation: "Platform Consultant",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 83,
    name: "M Anusha Reddy",
    company: "Quixy",
    designation: "Platform Consultant",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 84,
    name: "Mashetty Srivani",
    company: "Quixy",
    designation: "Platform Consultant",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 85,
    name: "Vidhya Rayapati",
    company: "Quixy",
    designation: "Platform Consultant",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 86,
    name: "K Soniya",
    company: "Ryan Tax",
    designation: "Tax Associate",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 87,
    name: "Kondapaneni Venu",
    company: "Ryan Tax",
    designation: "Tax Associate",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 88,
    name: "Amita Satpathy",
    company: "Ryan Tax",
    designation: "Tax Associate",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 89,
    name: "Madikatla Radhik Reddy",
    company: "Ryan Tax",
    designation: "Tax Associate",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 90,
    name: "Ch Preetham",
    company: "Ryan Tax",
    designation: "Tax Associate",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 91,
    name: "Chilukuri Spandana",
    company: "Ryan Tax",
    designation: "Tax Associate",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 92,
    name: "K Vinitha",
    company: "Ryan Tax",
    designation: "Tax Associate",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 93,
    name: "Kola Nithin Kumar",
    company: "Ryan Tax",
    designation: "Tax Associate",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 94,
    name: "Jinukala Siddhu Siddhu Jinukala",
    company: "SIS",
    designation: "Management Trainee",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 95,
    name: "Punna Govinda Raju Pavan Kumar",
    company: "SIS",
    designation: "Management Trainee",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 96,
    name: "Murali Manohar Telagamsetti",
    company: "SIS",
    designation: "Management Trainee",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 97,
    name: "Mandumula Akshay Kumar",
    company: "Stoneplus",
    designation: "BDE",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 98,
    name: "Mahanama Susheel Eagala",
    company: "Sneha Elevator",
    designation: "Senior Analyst - Portfolio Management Group",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 99,
    name: "Mayank Singh Sengar Sengar",
    company: "Sneha Elevator",
    designation: "Senior Analyst - Portfolio Management Group",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 100,
    name: "Atique Ur Rahman",
    company: "Homelane",
    designation: "Senior Analyst - Portfolio Management Group",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 101,
    name: "Varshini Reddy Bollampally",
    company: "Sneha Elevator",
    designation: "Senior Analyst - Portfolio Management Group",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 102,
    name: "Mubarak Vali Km",
    company: "Sneha Elevator",
    designation: "Senior Analyst - Portfolio Management Group",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 103,
    name: "Jyoti Choudhary",
    company: "UBS",
    designation: "Management Trainee - Investment Banking Operations",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 104,
    name: "Darur Moksha",
    company: "UBS",
    designation: "Management Trainee - Investment Banking Operations",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 105,
    name: "Bhavesh Kumar Tripathi",
    company: "UBS",
    designation: "Management Trainee - Investment Banking Operations",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 106,
    name: "Deekshitha Reddy",
    company: "UBS",
    designation: "Management Trainee - Investment Banking Operations",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 107,
    name: "Shri Hari Joshi",
    company: "UBS",
    designation: "Management Trainee - Investment Banking Operations",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 108,
    name: "Sowmya Ranjan Nayak",
    company: "UBS",
    designation: "Management Trainee - Investment Banking Operations",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 109,
    name: "Ayesha Begum",
    company: "Zomato",
    designation: "Key Account Manager",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 110,
    name: "Sri Pravalika Nisankam",
    company: "Zomato",
    designation: "Key Account Manager",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 111,
    name: "Sirgapur Yadagiri",
    company: "ZUDIO",
    designation: "Store Manager",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 112,
    name: "Tapsi Pradhan",
    company: "ZUDIO",
    designation: "Store Manager",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 113,
    name: "Shreya Barai",
    company: "Incor",
    designation: "Management Trainee",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 114,
    name: "Nikhitha Reddy Bhushi",
    company: "ITC",
    designation: "Sales Trainee",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 115,
    name: "D Sweshitha",
    company: "Novo Insurance",
    designation: "Business Development Executive",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 116,
    name: "Yogesh Sai Kumar Gollakaram",
    company: "Novo Insurance",
    designation: "Business Development Executive",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 117,
    name: "P Sruti",
    company: "Novo Insurance",
    designation: "Business Development Executive",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 118,
    name: "Dugyala Srija",
    company: "K12 Techno Services",
    designation: "PRM",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 119,
    name: "Narla Nagadeepika",
    company: "K12 Techno Services",
    designation: "PRM",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 120,
    name: "Puspanjali",
    company: "Cyepro Solutions",
    designation: "MT- Sales and Marketing",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 121,
    name: "Nazneen",
    company: "Cyepro Solutions",
    designation: "MT- Sales and Marketing",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 122,
    name: "R. Yogesh",
    company: "Cyepro Solutions",
    designation: "MT- Sales and Marketing",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 123,
    name: "Elluru Vandhana",
    company: "Cyepro Solutions",
    designation: "MT- Sales and Marketing",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 124,
    name: "Sirupa Shresta",
    company: "OYO",
    designation: "Demand Manager",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 125,
    name: "Pinni Vamsi Krishna",
    company: "Quixy",
    designation: "Platform Consultant",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 126,
    name: "Chidirala Varun Kumar",
    company: "Hacket Group", 
    designation: "Trainee – Business Development",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 127,
    name: "Kothamasu Ramya Krishna",
    company: "Vodafone",
    designation: "Cluster Trainee : Store Manager & Territory Sales Manager",
    year: "2023-25", 
    salary: "500",
  },
  {
    id: 128,
    name: "Sowmya Jaithwala",
    company: "Saxon AI",
    designation: "Lead Gen / Inside Sales Executive",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 129,
    name: "Sharmistha Das",
    company: "Value Momentum",
    designation: "HRBP - Operations",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 130,
    name: "Adirajapalli Vagdevi",
    company: "Lloyd Technologies",
    designation: "Learning Operation",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 131,
    name: "Revanth Kumar Goud Bolagani",
    company: "Lloyd Technologies",
    designation: "Learning Operation", 
    year: "2023-25",
    salary: "500",
  },
  {
    id: 132,
    name: "Chathurvedula Rashmitha",
    company: "S&P Global",
    designation: "Data Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 133,
    name: "K Varsha",
    company: "Factset",
    designation: "HR",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 134,
    name: "Prudhvishwar Reddy Mangalapally",
    company: "Intrainz Innovations Services",
    designation: "Business Development Executive",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 135,
    name: "Akula Sai Kumar Sai Kumar",
    company: "Intrainz Innovations Services",
    designation: "Business Development Executive",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 136,
    name: "Shaik Shoaib",
    company: "Frutolic",
    designation: "Manager – Business Development",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 137,
    name: "Belum Hema",
    company: "Fortune Global Organisation",
    designation: "Customer Relationship",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 138,
    name: "Monica Ande",
    company: "Quixy",
    designation: "Platform Consultant",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 139,
    name: "Poosa Yogesh Yogesh",
    company: "Intrainz Innovations Services",
    designation: "Business Development Executive",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 140,
    name: "Srinitha Rapolu",
    company: "Hetro Drugs",
    designation: "Learning and Development Officer",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 141,
    name: "Ragisetty Navya",
    company: "Trianz",
    designation: "Software Engineer Trainee",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 142,
    name: "Garaboina Nikhil",
    company: "Yes Bank",
    designation: "Branch Manager",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 143,
    name: "Aniket Sanjay Garte",
    company: "Zeneith Forex",
    designation: "Trainee/Executive – Sales",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 144,
    name: "Praveen Singh Gill",
    company: "Zeneith Forex",
    designation: "Trainee/Executive – Sales",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 145,
    name: "Dibakar Naskar",
    company: "Zeneith Forex",
    designation: "Trainee/Executive – Sales",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 146,
    name: "Khambum Venkata Ashwath Reddy",
    company: "Zeneith Forex",
    designation: "Trainee/Executive – Sales",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 147,
    name: "Sai Sri Harshita Pantula",
    company: "Axis Bank",
    designation: "Relationship Manager",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 148,
    name: "Bhanu Prasad Thalari",
    company: "SBI Life",
    designation: "Senior Associate",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 149,
    name: "Uddeshya Shrivastava",
    company: "SBI Life",
    designation: "Senior Associate",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 150,
    name: "Kurelli Geethika Goud",
    company: "Lead Winner",
    designation: "",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 151,
    name: "Pavan Kalyan Boda",
    company: "Global Data",
    designation: "Associate Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 152,
    name: "Devagari Prashanth",
    company: "Global Data",
    designation: "Associate Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 153,
    name: "Morsu Sahithi Reddy",
    company: "Global Data",
    designation: "Associate Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 154,
    name: "Akshay Kumar Jonnala",
    company: "Global Data",
    designation: "Associate Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 155,
    name: "Aashu Kumar Singh",
    company: "Pigeon Education Technology",
    designation: "Inside Sales",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 156,
    name: "Aftab Ahmed",
    company: "Pigeon Education Technology",
    designation: "Inside Sales",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 157,
    name: "Harshit Gupta",
    company: "Pigeon Education Technology",
    designation: "Inside Sales",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 158,
    name: "Yash Kumar Dandsena",
    company: "First Partner Consulting",
    designation: "Senior Process Associate",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 159,
    name: "Karanam Anantha Krishna Kashyap",
    company: "Cyepro Solutions",
    designation: "MT- Sales and Marketing",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 160,
    name: "Anushka Dubey",
    company: "Lloyd Technologies",
    designation: "Learning Operation",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 161,
    name: "Manisha Kumari",
    company: "HDFC Bank",
    designation: "PB Classic position",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 162,
    name: "Md Gulam Gaush",
    company: "HDFC Bank",
    designation: "PB Classic position",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 163,
    name: "Prachi Sharma",
    company: "IDFC First Bank",
    designation: "Associate Manager",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 164,
    name: "Harish Kumar Patel",
    company: "IDFC First Bank",
    designation: "Associate Manager",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 165,
    name: "Mounika Nandhu Busim",
    company: "IDFC First Bank",
    designation: "Associate Manager",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 166,
    name: "Deshpande Jahanavi",
    company: "IDFC First Bank",
    designation: "Associate Manager",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 167,
    name: "Itha Sai Charan Sai Charan",
    company: "IDFC First Bank",
    designation: "Associate Manager",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 168,
    name: "Sirigineedi Bala Sai Vinay",
    company: "IDFC First Bank",
    designation: "Associate Manager",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 169,
    name: "Sirisha Ummadisetty",
    company: "Global Data",
    designation: "Associate Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 170,
    name: "Ronit Ashok Wangalwar",
    company: "Global Data",
    designation: "Associate Analyst",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 171,
    name: "Nukala Jayanthi",
    company: "HDFC Bank",
    designation: "PB Classic position",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 172,
    name: "Revathi Surya Lakshmi Palanki",
    company: "HDFC Bank",
    designation: "PB Classic position",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 173,
    name: "Shanawaz Ali Shaik",
    company: "HDFC Bank",
    designation: "PB Classic position",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 174,
    name: "Shekhar Patwa",
    company: "HDFC Bank",
    designation: "PB Classic position",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 175,
    name: "M Vivek Goud",
    company: "HDFC Bank",
    designation: "PB Classic position",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 176,
    name: "Ambike Singh",
    company: "Value Momentum",
    designation: "HRBP - Operations",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 177,
    name: "Nitesh Prasad",
    company: "Value Momentum",
    designation: "Inside Sales",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 178,
    name: "Salman Hussain",
    company: "Value Momentum",
    designation: "Inside Sales",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 179,
    name: "Gosula Rishitha",
    company: "Value Momentum",
    designation: "Inside Sales",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 180,
    name: "Gummadi Sravani",
    company: "Value Momentum",
    designation: "Inside Sales",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 181,
    name: "Gudiganti Devendra Anil Kumar",
    company: "Value Momentum",
    designation: "Inside Sales",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 182,
    name: "Abhishek Manne",
    company: "Franklin Templeton",
    designation: "Trainee -Operations",
    year: "2023-25",
    salary: "500",
  },
  {
    id: 183,
    name: "Pushpa Choudhary",
    company: "UPS Logistics",
    designation: "Assistant Manager",
    year: "2023-25",
    salary: "500",
  },
];
