export const studentsData = [
  {
    id: 1,
    name: "Neetish Prasad",
    company: "Homelane",
    program: "TPS",
    location: "Chattisgarh, Chattisgarh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 2,
    name: "Alankar Sinha",
    company: "Homelane",
    program: "TPS",
    location: "Chattisgarh, Chattisgarh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 3,
    name: "Salman Hussain",
    company: "Homelane",
    program: "TPS",
    location: "Chattisgarh, Chattisgarh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 4,
    name: "Khushi Dangre",
    company: "Eteam",
    program: "TPS",
    location: "Chattisgarh, Chattisgarh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 5,
    name: "Aditi Sharma",
    company: "HDFC LIFE",
    program: "TPS",
    location: "Chattisgarh, Chattisgarh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 6,
    name: "Ayesha Begum",
    company: "Praval Infotech",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 7,
    name: "K Shirisha",
    company: "Digital Nest",
    program: "TPS",
    location: "Srikakulam, Andhra Pradesh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 8,
    name: "Anshu Masih",
    company: "Berkadia",
    program: "TPS",
    location: "Bilaspur, Chattisgarh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 9,
    name: "Manisha Chikka",
    company: "Oxane Partners",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 10,
    name: "Vishnubhatla Naga Bhargavi",
    company: "KPMG",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 11,
    name: "Rohan Gotiwada",
    company: "Asian Paints",
    program: "TPS",
    location: "Bilaspur, Chattisgarh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 12,
    name: "Manisha Prasad",
    company: "Berkadia",
    program: "TPS",
    location: "Kolkata, West Bengal",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 13,
    name: "M Hamsini",
    company: "Praval Infotech",
    program: "TPS",
    location: "Karimnagar, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 14,
    name: "A Akshita",
    company: "Codeyoung",
    program: "TPS",
    location: "Bilaspur, Chattisgarh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 15,
    name: "M Anusha Reddy",
    company: "Quixy",
    program: "BA",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 16,
    name: "Nilesh kumar Deheri",
    company: "KPMG",
    program: "BIFS",
    location: "Sonepur, Odissa",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 17,
    name: "Khoosbu Gosai",
    company: "Deloitte",
    program: "TPS",
    location: "Raipur, Chattisgarh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 18,
    name: "Kunchala Kishore",
    company: "Asian Paints",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "http",
    year: 2023,
    salary: "500",
  },
  {
    id: 19,
    name: "Ayushi kumari",
    company: "Praval Infotech",
    program: "TPS",
    location: "Gaya, Bihar",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 20,
    name: "Ashitha Bhawana Sharma",
    company: "Oxane Partners",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 21,
    name: "Ritesh Kumar",
    company: "HDFC LIFE",
    program: "TPS",
    location: "East Champaran, Bihar",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 22,
    name: "Parbati Ghosh",
    company: "Berkadia",
    program: "TPS",
    location: "Durgapur, West Bengal",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 23,
    name: "Subhajeet Pan",
    company: "Asian Paints",
    program: "TPS",
    location: "Durgapur, West Bengal",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 24,
    name: "Mainak Shyam",
    company: "Aditya Birla Sunlife Mutual Funds",
    program: "TPS",
    location: "Durgapur, West Bengal",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 25,
    name: "V Aakansha Rao",
    company: "Berkadia",
    program: "TPS",
    location: "Bilaspur, Chattisgarh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 26,
    name: "Akshay Thakur",
    company: "Berkadia",
    program: "TPS",
    location: "Ambikapur, Chattisgarh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 27,
    name: "Srivani Mashetty",
    company: "Quixy",
    program: "BA",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 28,
    name: "Aman Kumar Singh",
    company: "Asian Paints",
    program: "TPS",
    location: "Jamshedpur, Jharkhand",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 29,
    name: "Chandana Naikal",
    company: "Lloyds Technology Centre",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 30,
    name: "Mayank Singh Sengar",
    company: "Sneha Elevator",
    program: "TPS",
    location: "Ratlam, Madhya Pradesh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 31,
    name: "Bhavani Sidhu Gunti",
    company: "HDFC LIFE",
    program: "BIFS",
    location: "Chirala, Andhra Pradesh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 32,
    name: "Alankar Chakraborty",
    company: "Oxane Partners",
    program: "TPS",
    location: "Secunderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 33,
    name: "Mahanama Susheel Eagala",
    company: "Sneha Elevator",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 34,
    name: "Desu Vasavi",
    company: "Berkadia",
    program: "TPS",
    location: "TUNI, Andhra Pradesh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 35,
    name: "Prakhar Singh",
    company: "Oxane Partners",
    program: "BIFS",
    location: "MEDCHAL, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 36,
    name: "Nomula sameeksha",
    company: "Deloitte",
    program: "BIFS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 37,
    name: "Avala Deepika",
    company: "HDFC LIFE",
    program: "BIFS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 38,
    name: "Arkatavemula Varalakshmi",
    company: "Godrej Jersey",
    program: "TPS",
    location: "PRODDATUR, Andhra Pradesh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 39,
    name: "Katam Vijayalakshmi",
    company: "KPMG",
    program: "TPS",
    location: "PRODDATUR, Andhra Pradesh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 40,
    name: "Bollampally Varshini Reddy",
    company: "Sneha Elevator", 
    program: "TPS",
    location: "Hyderabad, TELANGANA",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 41,
    name: "Rayapati vidhya",
    company: "Quixy",
    program: "BA", 
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 42,
    name: "Konanki Priyanka",
    company: "Berkadia",
    program: "TPS",
    location: "Anantapur, Andhra Pradesh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 43,
    name: "Dwarampudi Bhuvana Sri Ahalya",
    company: "Godrej Jersey",
    program: "TPS",
    location: "RAJAHMUNDRY, Andhra Pradesh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 44,
    name: "Gajja Harshitha",
    company: "Berkadia",
    program: "BIFS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 45,
    name: "Chervirala Vedhavathi",
    company: "Berkadia",
    program: "BIFS",
    location: "Hyderabad, TELANGANA",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 46,
    name: "Sunkara Kalyan",
    company: "Asian Paints",
    program: "TPS",
    location: "Nallajerla, Andhra Pradesh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 47,
    name: "Bondili Renuka Bai",
    company: "KPMG",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 48,
    name: "M Durga Manish",
    company: "Praval Infotech",
    program: "TPS",
    location: "NIZAMABAD, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 49,
    name: "Sravya Kanuganti",
    company: "Homelane",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 50,
    name: "Busala Usha Sandhya",
    company: "Berkadia",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 51,
    name: "Allam Sneha",
    company: "Quixy",
    program: "BA",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 52,
    name: "Kolati Ajay Raja",
    company: "Berkadia",
    program: "TPS",
    location: "ANAKAPALLE, Andhra Pradesh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 53,
    name: "Nareddy Venkateshwar Reddy",
    company: "Lloyds Technology Centre",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 54,
    name: "Boppudi Naganjini Anjana",
    company: "Homelane",
    program: "TPS",
    location: "GUNTUR, Andhra Pradesh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 55,
    name: "K M Mubarak Vali",
    company: "Sneha Elevator",
    program: "TPS",
    location: "Secunderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 56,
    name: "Sukhvinder Kour",
    company: "Praval Infotech",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 57,
    name: "Gampa Abhishek",
    company: "Aditya Birla Sunlife Mutual Funds",
    program: "TPS",
    location: "Nirmal, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 58,
    name: "K V V S R Varun",
    company: "Oxane Partners",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 59,
    name: "Tallari Bhanuprasad",
    company: "Asian Paints",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 60,
    name: "Hema Latha Reddy Marthala",
    company: "Godrej Jersey",
    program: "TPS",
    location: "Vijayawada, Andhra Pradesh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 61,
    name: "Tapsi Pradhan",
    company: "ZUDIO",
    program: "TPS",
    location: "Rayagada, Odissa",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 62,
    name: "M Jyothsna",
    company: "Berkadia",
    program: "BIFS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 63,
    name: "Bandapally Madhurita",
    company: "Homelane",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 64,
    name: "Allam Dinesh",
    company: "Berkadia", 
    program: "TPS",
    location: "Jeypore, Odissa",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 65,
    name: "Atique Ur Rahman",
    company: "Sneha Elevator",
    program: "TPS", 
    location: "Warangal, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 66,
    name: "Purma Jyoshna Reddy",
    company: "Homelane",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 67,
    name: "Gondimalla Gurusai",
    company: "KPMG",
    program: "TPS",
    location: "Nizamabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 68,
    name: "Vemula Akash",
    company: "Big Basket",
    program: "BIFS",
    location: "Pargi, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 69,
    name: "J Abhiram",
    company: "HDFC LIFE",
    program: "BIFS",
    location: "Ramagundam, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 70,
    name: "Atiketi Hanish",
    company: "Aditya Birla Sunlife Mutual Funds",
    program: "BIFS",
    location: "Ramagundam, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 71,
    name: "Shivam Vishwakarma",
    company: "KPMG",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 72,
    name: "Sirgapur Yadagiri",
    company: "ZUDIO",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 73,
    name: "Kannappa Reddy Jayalakshmi",
    company: "ICICI Securities",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 74,
    name: "Kondipati Govardhan",
    company: "KPMG",
    program: "BIFS",
    location: "Rajampet, Andhra Pradesh",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 75,
    name: "A V Tejasvin",
    company: "Codeyoung",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 76,
    name: "Kandukuri Varun",
    company: "Asian Paints",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 77,
    name: "Donepudi Nikhila",
    company: "KPMG",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 78,
    name: "V V Harshita",
    company: "Codeyoung",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 79,
    name: "Velemineti Archana",
    company: "Deloitte",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 80,
    name: "Aniket Sanjay Garte",
    company: "IDFC FIRST BANK",
    program: "TPS",
    location: "Latur, Maharastra",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 81,
    name: "Runja N Chaturvedi",
    company: "IDFC FIRST BANK",
    program: "BIFS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 82,
    name: "Venu Kumar",
    company: "IIISTUDIO",
    program: "TPS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 83,
    name: "Anil Kumar Yadav",
    company: "IDFC FIRST BANK",
    program: "BIFS",
    location: "Hyderabad, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 84,
    name: "Jukanti Varun Reddy",
    company: "Homelane",
    program: "TPS",
    location: "Kamareddy, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
  {
    id: 85,
    name: "Samala Rohan",
    company: "Homelane",
    program: "TPS",
    location: "Kamareddy, Telangana",
    linkedin: "",
    year: 2023,
    salary: "500",
  },
];
