export const industryData = [
    {
      id: 1,
      image: "https://v0.dev/placeholder.svg",
      date: "October 25, 2022",
      category: "education",
      title: "Visit @BSE Ltd.",
      tags: ["Finance", "Stock Market", "Learning"],
      description: `The Students of Institute of Marketing and Management PGDM batch 2022-24 visited BSE New Delhi office on September 6, 2022. The visit was facilitated by the IMM Finance Club- Bear and Bull. It was a knowledge enriching experience for the students. The visit started with an informative session about the Financial Markets of India. The session was presided by Mr. Harbinder Singh Sokhi, Manager Investor Protection Fund BSE. Mr. Singh elaborated on the importance of well-established markets, transparent market operations and investor awareness initiatives. The students got an opportunity to see the live market and understand how the transactions happen in real time. Next session was taken over by Mr. Pulock Bhattacharji, Vice President - Business Development, Skilling, Training & Placement BSE Institute Ltd. He elaborated on various courses related to the stock market that BSE India conducts to equip students with additional skills when it comes to trading and investment. It was a very enlightening and knowledge enriching experience. The Students felt motivated and inspired to start their investment journeys soon.`,
      gallery: [],
    },
    {
      id: 2,
      image: "https://v0.dev/placeholder.svg",
      date: "November 15, 2022",
      category: "education",
      title: "Visit @Coca Cola",
      tags: ["Beverage", "Innovation", "Learning"],
      description: `Experience the journey of discovery, learning, and inspiration. Imparting firsthand insights into operations, innovation strategies, and market dominance with our exclusive industry visits to Coca-Cola, organized for the PGDM Batch of 2023-25.`,
      gallery: [],
    },
    {
      id: 3,
      image: "https://v0.dev/placeholder.svg",
      date: "December 1, 2022",
      category: "education",
      title: "Visit @Yakult",
      tags: ["Health", "Innovation", "Learning"],
      description: `Every industrial revolution brings along a learning revolution. IMM India recently organized industrial visits to Yakult, providing valuable industrial exposure and insightful business perspectives to the PGDM Batch of 2023-25.`,
      gallery: [],
    },
    {
      id: 4,
      image: "https://v0.dev/placeholder.svg",
      date: "January 12, 2023",
      category: "education",
      title: "CISCO Network Training @ Network Bulls",
      tags: ["IT", "Networking", "Learning"],
      description: `Institute of Marketing & Management organized an Industrial Visit to CISCO Network Training at Network Bulls, Gurgaon, for its PGDM 2023 -2025 batch and PGDM 2022 -2024 batch (Information Technology Specialisation) students on 12th January 2023. The students underwent in-depth training on CISCO Networking Concepts from CISCO-Certified Trainers Mr. Surrender, Mr.Pramod and Mr. Pankaj. The students were given practical exposure to routers and switches in CISCO Lab. The student not only gained knowledge of networking concepts but also acquired hands-on experience. Dr. Smita Agarwal and Ms. Nisha Anand accompanied the students for the visit.`,
      gallery: [],
    },
    {
      id: 5,
      image: "https://v0.dev/placeholder.svg",
      date: "October 12, 2022",
      category: "education",
      title: "Visit @Coca-Cola Happiness Factory",
      tags: ["Beverage", "Manufacturing", "Learning"],
      description: `Institute of Marketing & Management organized an Industrial Visit to COCA-COLA Happiness Factory, Greater Noida and India's Only Happiness Factory Museum, for a group of 1st year PGDM students on 12th October 2022. The visit was conducted for the young student managers with an intent to understand about product line, product manufacturing, packaging, supply chain and inventory management. The students observed the entire operational process of the Coca Cola product range (e.g., Mazaa, Limca, Minute Maid, Coca Cola, Thums-up, Fanta, Kinley Water, etc.) in bottles and cans of different sizes. Then informative and interactive session was delivered by Ms Samar & Ms Richa who made the students understand nuances of beverage production through “see and know" concept. Students had a great enthusiasm to understand the various aspects of the business. They were briefed upon the safety, pollution and energy efficiency norms being met by the bottling plant. The students were also acquainted about the CSR projects of Coca-Cola e.g., setting up sanitary facilities for girls in rural schools and improving the livelihood of the farmers by providing them assistance for the cultivation of mangoes. Coca-Cola also works towards a more sustainable future by reducing carbon footprint and maximizing water conservation by ensuring minimum water wastage by reusing, recycling and replenishing the water used in the plant. The Happiness Factory also had an exciting section of virtual reality games, the set of coke studio, and a polar bear along with stunning posters of with old advertisements of Coca-Cola adorning the lounge walls. The visit was a learning experience for the students, as it provided a practical approach towards the concept of company, branding and products. Students came to know about the implementation of different processes by the company to provide excellent service to the consumers that makes it one of the world's most cherished trademark.`,
      gallery: [],
    },
    {
      id: 6,
      image: "https://v0.dev/placeholder.svg",
      date: "September 9, 2022",
      category: "sports",
      title: "Visit @Shooting Range",
      tags: ["Sports", "Training", "Activity"],
      description: `IMM Sports Club "IMM SQUAD" organized a sports activity to Shooting Range on 9th September 2022, where they were introduced to shooting and equipments under the guidance of professional trainers, who helped them in understanding the techniques and methods of using the equipments. The activity was organized in GD Goenka Education Society, Sohna Road. 30 students participated in this activity. They were allowed to take 30 shots comprising of 15 shots on the pistol and 15 on the rifle. The activity was an overall fun filled day, a day of new learning techniques. Prof. Shubhra Samaddar & Dr. Swati Jha had accompanied the students and they also tried their hands on shooting.`,
      gallery: [],
    },
    {
      id: 7,
      image: "https://v0.dev/placeholder.svg",
      date: "April 11, 2022",
      category: "finance",
      title: "Visit @SEBI",
      tags: ["Finance", "Regulation", "Investment"],
      description: `The Industry Visit to SEBI was organised for students on 11th April, 2022 to understand various roles & responsibilities of the Exchange. Ms. Nanu Kaur – DGM, SEBI, Mr. Harbinder Singh Sokhi and Mr. Shree Ram from SEBI discussed the concept of Wealth Creation and the Importance of Fund-Raising Cycle for an Entrepreneur. They discussed investment options like Stock Market and Crypto Currency, working of SEBI and various Powers of SEBI and the procedure for recording complaints & grievances. This enriching visit was coordinated by Dr. Tanu Manocha and Prof. Nisha Anand and a great learning session for all students as they learnt practical insights and experiences from SEBI professionals.`,
      gallery: [],
    },
    {
      id: 8,
      image: "https://v0.dev/placeholder.svg",
      date: "October 8, 2021",
      category: "retail",
      title: "Visit @Pantaloons",
      tags: ["Retail", "Fashion", "Business"],
      description: `Continuing with the Industry Visit Series, a group of first year Students visited The Pantaloons Retail Outlet at the Ambience Mall, Gurgaon. Dr. Swati Jha and Prof Sakshi Sharma accompanied the group. They were given an in-depth insight on the functioning of this leading retail brand by Mr. Piyush Rath, Head Operations Pantaloons. This visit ended with Students receiving gift vouchers from Pantaloons, for shopping, which was thoroughly enjoyed by all.`,
      gallery: [],
    },
    {
      id: 9,
      image: "https://v0.dev/placeholder.svg",
      date: "October 8, 2021",
      category: "virtual",
      title: "Virtual Tour @Yakult",
      tags: ["Health", "Manufacturing", "Virtual"],
      description: `On 8th October 2021 IMM conducted a Virtual Industry Visit at Yakult. It was a wonderful initiative by IMM, to making it a 'Yakult Day at Campus'. Students learnt about the day-to-day operations that takes place at Yakult. They were taught about how the distribution of Yakult Probiotic Drinks is conducted. It was indeed an enriching and knowledgeable visit@Yakult conducted by Yakult team. As a gesture and to inculcate the habit of building a great immune system, IMM provided Yakult probiotic drinks to all the Students attending the Virtual Industry Visit at Yakult.`,
      gallery: [],
    },
    {
      id: 10,
      image: "https://v0.dev/placeholder.svg",
      date: "September 22, 2021",
      category: "retail",
      title: "Visit @DLF Emporio & Promenade",
      tags: ["Retail", "Luxury", "Mall Management"],
      description: `A group of Students visited the DLF Malls-Emporio @dlfemporio & Promenade @dlfpromenade to understand the back-end operations and working of luxury malls in Vasant Kunj, New Delhi. They were given a detailed guided tour and briefing by Mr. Rajesh Singh Deputy Manager of DLF Malls-Emporio & Mr. Ishaan Raj Operations Manager DLF Promenade Mall Operations. Students thoroughly enjoyed this fun filled yet insightful visit and learnt in detail about Mall Management.`,
      gallery: [],
    },
    {
      id: 11,
      image: "https://v0.dev/placeholder.svg",
      date: "September 22, 2021",
      category: "manufacturing",
      title: "Visit @Mother Dairy",
      tags: ["FMCG", "Manufacturing", "Food Processing"],
      description: `Students of IMM visited the Mother Dairy plant in Patparganj, New Delhi, which is counted as the largest plant in Asia, on 22nd & 23rd September 2021. The visit was organized to enable the Students to have an understanding the process and manufacturing of quality of milk and other edible products in India. The Company also has a diversified portfolio with edible products like oils & fruits, vegetables, frozen vegetables that is required to meet the daily requirements of the household.`,
      gallery: [],
    },
    {
      id: 12,
      image: "https://v0.dev/placeholder.svg",
      date: "September 22, 2021",
      category: "manufacturing",
      title: "Visit @Liberty Shoes",
      tags: ["Manufacturing", "Footwear", "Production"],
      description: `IMM Students of PGDM 2020-22 Batch undertook an industry visit to the manufacturing unit of Liberty Shoes Company located at Karnal, Haryana, on Wednesday, 22nd September, 2021. The visit was guided by Mr. Hemant Mohan, Head- Institutional Sales and Mr. Mishra, from HR department. They facilitated the company tour and shared information about current trends in production techniques and how Liberty Shoes brand was established. Students got a chance to understand the production mechanism and other management functions at Liberty. They understood the actual working of manufacturing process in footwear industry.`,
      gallery: [],
    },
    {
      id: 13,
      image: "https://v0.dev/placeholder.svg",
      date: "2021",
      category: "retail",
      title: "Visit @Central Cottage Emporium",
      tags: ["Handicrafts", "Retail", "Culture"],
      description: `The Students of 2021-2023 were taken to the Central Cottage Industries Emporium in New Delhi where they were exposed to a variety of handicrafts by skilled artisans from all over the country. The Emporium and its marketing serves as a window to India by means of display and sale of artistic objects. They got an in-depth knowledge on the handicraft industry in India. The visit ended with a surprise gift for all Students.`,
      gallery: [],
    },
    {
      id: 14,
      image: "https://v0.dev/placeholder.svg",
      date: "2021",
      category: "art",
      title: "Visit @Vadehra Art Gallery",
      tags: ["Art", "Gallery", "Culture"],
      description: `The Students of IMM were taken to the Vadhera Art Gallery where they learned about the intricate inner workings of the art world. They were introduced to exotic pieces of art in the modern world, learnt about art appreciation and also were walked through the process of Gallery Management as well as the entire auction process.`,
      gallery: [],
    },
    {
      id: 15,
      image: "https://v0.dev/placeholder.svg",
      date: "2020",
      category: "entertainment",
      title: "Visit @PVR Cinemas",
      tags: ["Entertainment", "Cinema", "Management"],
      description: `IMM Students of PGDM Batch (2020-22) got the privilege to visit a functional unit of PVR Cinemas, Faridabad. After a lockdown situation, it was the ice breaking activity for the Students. Students were introduced to the functions of Cinema Theatre Management, detailing how the movie is displayed on large screen, and the mechanism of running the reel behind the screen. The process of film distribution, bookings and reservations were also a part of hearing agenda during the visit. Students were thrilled to have a better understanding of the functioning of this important part of the entertainment industry.`,
      gallery: [],
    },
  ];